"""
preprocessing_qc
================

Quality-control (QC) metrics and visualizations for the pipeline's dMRI
preprocessing stage.

This subpackage only READS outputs already generated by the preprocessing steps
(denoising, topup, eddy, bias) and turns them into ``pandas`` tables and
``matplotlib`` figures. It does not run or modify any external tool
(FSL / MRtrix / ANTs).
"""

from .qc_metrics import (
    load_movement_rms,
    load_motion_parameters,
    load_outlier_map,
    summarize_outliers,
    load_qc_json,
    qc_json_to_series,
    compute_denoising_snr,
    compute_residual_stats,
    summarize_shells,
    subject_qc_summary,
    cohort_qc_summary,
)
from .qc_plots import (
    plot_before_after_slice,
    plot_movement_rms,
    plot_motion_parameters,
    plot_outlier_heatmap,
    plot_shells,
    plot_cnr_per_shell,
    plot_cohort_metric,
)

__all__ = [
    "load_movement_rms", "load_motion_parameters", "load_outlier_map",
    "summarize_outliers", "load_qc_json", "qc_json_to_series",
    "compute_denoising_snr", "compute_residual_stats", "summarize_shells",
    "subject_qc_summary", "cohort_qc_summary",
    "plot_before_after_slice", "plot_movement_rms", "plot_motion_parameters",
    "plot_outlier_heatmap", "plot_shells", "plot_cnr_per_shell",
    "plot_cohort_metric",
]
